### ISSUE TITLE
Ajouter bande annonce

### ISSUE THREAD

**Issue by JOniiX** [Azahet/Cpasnien.io-Downloader#1]
Salut, j'ai ajouté une fonction pour voir la bande annonce d'un film qu'on à sélectionner dans la listbox avec le contextmenustrip (j'ai juste mis une recherche sur google, il y a possibilité d'utiliser une API d'Allociné ou bien OMDB).

```
Private Sub bande_annonce()
        Dim film As String = ListBox1.SelectedItem
        Dim words() As String = {"DVDRIP", "DVDSCR", "FRENCH", "VOSTFR", "WEBRIP", "HDTV", "FINAL"}

        For Each elem As String In words
            film = film.Replace(" " + elem, "")
        Next
        Process.Start("https://www.google.fr/#q=" + film + " bande annonce")
End Sub
```

**Comment by Azahet** [comment]
Très bonne idée, je l'ai ajoutée. **Merci à toi !**
